# FurnitureLib config
# Made by Ste3et_C0st

# Version: 3.0.1

config-version: 4 #do not touch these option
storage-options:
  
  # Save Furniture in the Interval of nSecounds (-1 mean disable autosave)
  auto-save-interval: 300
  auto-save-console-message: true
  
  # Only LEGACY is avaiable right now
  storage-methode: LEGACY
  
  # Avaiable storage-type[SQLITE,Mysql]
  storage-type: SQLITE
  adress: localhost
  database: furniture
  user: ROOT
  password: 123abcdefg
  port: 3306
  
  auto_convert: false
  importCheck: false
  
  # These are additional settings for MySQL connections.
  # You should only change these settings if you know what you're doing.
  database-pool-settings:
    maximum-pool-size: 10
    idleTimeout: 10
    minimum-idle: 10
    maximum-lifetime: 1800000
    connection-timeout: 5000
  
  # These properties will most likely not need changing unless you encounter issues.
  connection-properties:
    # You may want to disable this if you are getting SSL errors,
    # However, we always recommend you use SSL where possible.
    useSSL: true
    allowPublicKeyRetrieval: false
    
  database-table-old: FurnitureLib_Objects #these option is the legacy Furniture Table to migrate from 1.12 to 1.13 DO NOT CHANGE THAT

general-options:
  useMetrics: true # Allow FurnitureLib to collect some data about your system and send them to https://bstats.org/plugin/bukkit/FurnitureLib/454
  debugMode: false # Enable or disable the Debug mode, these mode can spam you console but nice to debug stuff
  language: EN_en # Avaiable Language [EN_en, DE_de, PL_pl, FR_fr, RU_ru, CN_cn]
  useParticles: true # Allow to spawn Destroy Particles
  disableSitting: false # Allow to sit on Furniture Models
  glowing: true # Allow to glow the ArmorStands
  checkForUpdate: true # Allow to check for Plugin Updates
  rotateOnSit: true # Allow to rotate the Player Sight to the right direction on model sit

world-options:
  whitelist: false # if these option is false then the world list is a blacklist
  worlds: # a list of worlds who is whitelisted or blacklisted
    - first_demo_world
    - secound_demo_world
  viewRange: 10 # the plugin intern simulation distance
  packetRenderMethode: false # send the furniture models if the player move packet have been triggered

limit-options:
  limitConfig: PERMISSION,PLAYER # there is only these options avaiable: PERMISSION, PLAYER, WORLD, CHUNK you can simple combine then and the FurnitureLib use the config with the lowest value limitConfig: "PERMISSION,PLAYER"
  limitGlobal: 150 # PERMISSION: You can give your player the permissions furniture.globallimit.# | furniture.globallimit.125 -> let the player can place 125 furnitures objects it override the limitconfig

creative-options:
  removeItems: false # remove the item if it placed via creative
  interact-with-models: true # player in creative can interact with the furniture
  place-models: true # player in creative can place the models

model-protection:
  place-models-in-mode: PRIVATE # place models for PRIVATE (Only the Builder and Friends can use it) or PUBLIC (Everyone can use it)
  action: INTERACT # "INTERACT/BREAK/BREAK_INTERACT" : it means the player have permissions to interact or break another Furnitures !

hook:
  ProtectionLib:
    RegionMemberAccess: false # the owner of an region have acces to all FurnitureModels on his region
  Floodgate:
    hideModelsForBedrockClients: true # hide furniture models for BedrockClients because the Armorstand System in the Bedrock Edition is limited https://minecraft.fandom.com/wiki/Armor_Stand

purge-options:
  enable: false # disable or enable the purge system
  time: 30 # time in days
  removePurge: false # remove old furniture models from the world

antispam-options:
  place-delay:
    enable: true
    time: 5
  break-delay:
    enable: true
    time: 5
  timeDisplay: mm:ss:SSS
