stages:
  - build
  - bundle

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build-main:
  stage: build
  image: gradle:8.11-jdk17
  script:
  - chmod +x gradlew
  - ./gradlew -PsnapshotVersion=$CI_COMMIT_SHORT_SHA :FurnitureLib-Core:build :FurnitureLib-Paper:build :FurnitureLib-1_19_4:build
  artifacts:
    paths:
    - FurnitureLib-Core/build/libs/*.jar
    - FurnitureLib-Paper/build/libs/*.jar
    - FurnitureLib-1_19_4/build/libs/*.jar
    expire_in: 1 week

build-dispaly:
  stage: build
  image: gradle:8.11-jdk11
  script:
  - chmod +x gradlew
  - ./gradlew -PsnapshotVersion=$CI_COMMIT_SHORT_SHA -PcjavaVersion=11 :FurnitureLib-1_19_4:build
  artifacts:
    paths:
    - FurnitureLib-1_19_4/build/libs/*.jar
    expire_in: 1 week

build-folia:
  stage: build
  image: gradle:8.11-jdk21
  script:
  - chmod +x gradlew
  - ./gradlew -PsnapshotVersion=$CI_COMMIT_SHORT_SHA -PcjavaVersion=21 :FurnitureLib-Folia:build
  artifacts:
    paths:
    - FurnitureLib-Folia/build/libs/*.jar
    expire_in: 1 week
bundle:
  stage: bundle
  image: gradle:8.11-jdk17
  needs:
    - job: build-main
      artifacts: true
    - job: build-dispaly
      artifacts: true
    - job: build-folia
      artifacts: true
  script:
    - chmod +x ./gradlew || true
    - ./gradlew --version
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/FurnitureLib.jar
    expire_in: 1 week