stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

# 🟢 Java 17 Build (alles außer Folia)
build-main:
  stage: build
  image: gradle:8.11-jdk17
  script:
    - ./gradlew -PsnapshotVersion=$CI_COMMIT_SHORT_SHA :FurnitureLib-Core:build :FurnitureLib-Paper:build :FurnitureLib-1_19_4:build
    - ./gradlew copyJarToBin
  artifacts:
    paths:
      - build/libs/FurnitureLib.jar
    expire_in: 1 week
  only:
    - master

# 🔥 Java 21 Build (nur Folia)
build-folia:
  stage: build
  image: gradle:8.11-jdk21
  script:
    - ./gradlew -PsnapshotVersion=$CI_COMMIT_SHORT_SHA :FurnitureLib-Folia:build
  artifacts:
    paths:
      - FurnitureLib-Folia/build/libs/*.jar
    expire_in: 1 week
  only:
    - master

after_script:
  - echo "End CI"