name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Ste3et_C0st
website: ${project.url}
softdepend: [ProtocolLib,ProtectionLib,LightAPI,Multiverse,Multiverse-Core,MultiWorld,Vault,Hyperverse]
main: de.Ste3et_C0st.FurnitureLib.main.FurnitureLib
api-version: 1.13
commands:
  furniture:
    description: Furniture Command
    usage:  /<command>

permissions:
  furniture.hide:
      default: false
      description: Hide all Furnitures if that permissions is set!
  furniture.player:
    children:
      furniture.command.help: true
      furniture.command.recipe: true
      furniture.craft.*: true
      furniture.place.*: true
      furniture.sit.*: true
      furniture.model.sit: true
      furniture.command.toggle: true
      furniture.command.manage: true
  furniture.admin:
    children:
      furniture.command.debug: true
      furniture.command.list: true
      furniture.command.list.plugin: true
      furniture.command.list.type: true
      furniture.command.list.world: true
      furniture.command.remove: true
      furniture.command.remove.distance: true
      furniture.command.remove.obj: true
      furniture.command.remove.plugin: true
      furniture.command.remove.type: true
      furniture.command.remove.all: true
      furniture.command.remove.player: true
      furniture.command.remove.world: true
      furniture.command.remove.lookat: true
      furniture.command.give: true
      furniture.command.give.other: true
      furniture.command.manage.other: true
      furniture.command.purge: true
      furniture.command.manage: true
      furniture.command.toggle.other: true
      furniture.command.download: true
      furniture.command.delete: true
      furniture.command.create: true
      furniture.command.edit: true
      furniture.command.upload: true
      furniture.command.import: true
      furniture.limit.bypass: true
      furniture.bypass.breakSpam: true
      furniture.bypass.placeSpam: true
      furniture.toggle: true
      furniture.update: true
      ProtectionLib.admin: true
      furniture.player: true
