name: FurnitureLib
version: 1.9.9.8
description: FurnitureLib is an Libary to make ArmorStand creations easer
author: Ste3et_C0st
website: http://dicecraft.de
depend: [ProtocolLib]
softdepend: [ProtectionLib,LightAPI,Multiverse,Multiverse-Core,Multiworld,PlotSquared,HolographicDisplays, Vault, ASkyBlock, WirelessRedstone]
main: de.Ste3et_C0st.FurnitureLib.main.FurnitureLib
commands: 
  furniture:
    description: Furniture Command
    usage:  /<command>

permissions:
  furniture.player:
    children:
      furniture.help: true
      furniture.recipe: true
      furniture.crafting.*: true
      furniture.craft.*: true
      furniture.place.*: true
      furniture.toggle: true
      furniture.manage: true
  furniture.admin:
    children:
      furniture.debug: true
      furniture.list: true
      furniture.list.plugin: true
      furniture.list.type: true
      furniture.list.world: true
      furniture.remove: true
      furniture.remove.distance: true
      furniture.remove.obj: true
      furniture.remove.plugin: true
      furniture.remove.type: true
      furniture.remove.all: true
      furniture.remove.player: true
      furniture.remove.world: true
      furniture.remove.lookat: true
      furniture.give: true
      furniture.give.player: true
      furniture.limit.bypass: true
      furniture.manage.other: true
      furniture.purge: true
      furniture.bypass.breakSpam: true
      furniture.bypass.placeSpam: true
      furniture.help: true
      furniture.recipe: true
      furniture.crafting.*: true
      furniture.place.*: true
      furniture.toggle: true
      furniture.manage: true
      furniture.toggle.another: true
      furniture.download: true
      furniture.delete: true
      furniture.create: true
      furniture.edit: true
      furniture.upload: true
      furniture.update: true
      furniture.import: true
      ProtectionLib.admin: true
      furniture.player: true